# Generated by Django 4.2.4 on 2023-09-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Card_Id', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtual_id',
            name='img',
            field=models.ImageField(blank='True', null='True', upload_to='images'),
            preserve_default='True',
        ),
    ]
